# Generated by Django 5.2.5 on 2025-08-23 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_channel_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='subscribe',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
